### PR TITLE
Ensure eval call knows its line numbers etc

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds binding and line number information to an eval'd piece of code.

### CODE REVIEW

**Review by marvindanig — APPROVED** [review]
Neat.

**Comment by n-rodriguez** [comment]
Hi there! Any news? ping @kjvarga

**Comment by n-rodriguez** [comment]
@olleolleolle hello! can you please rebase your branch? Thank you!

**Comment by olleolleolle** [comment]
@n-rodriguez Now rebased!

**Comment by kjvarga** [comment]
@olleolleolle @n-rodriguez I've removed the CircleCI Webhook from settings so it shouldn't show up in the status checks.  But looks like we might have to push an empty commit to clear out the errored job.

**Comment by n-rodriguez** [comment]
@olleolleolle @kjvarga  Thank you!

**Pull request merged**
