### PR TITLE
Add google storage support for remote uploads

### PR DESCRIPTION
**Pull request by raviy06**
Hi @kjvarga,

I have added `GoogleStorageAdapter` to support remote uploads Google Cloud Storage. Pease review the PR. I am already using this in one of my application, so I know that this works. I saw an issue for Google Storage so I thought I'd help out.

Let me know if there's an issue.

### CODE REVIEW

**Comment by kjvarga** [comment]
Thanks!  I’m quite busy at the moment but will review in the next couple weeks.

**Comment by kam1kaze** [comment]
@kjvarga do you have any ETA about such PR? We would like to use such feature.

**Comment by kjvarga** [comment]
Thanks for the pull request.  I've gotten around this this in my Christmas break :)  I've made some changes but your configuration should still work.  

Could you test it out and make sure it's working for you?  https://rubygems.org/gems/sitemap_generator/versions/6.1.0

**Comment by kjvarga** [comment]
Merged in https://github.com/kjvarga/sitemap_generator/pull/340

**Pull request merged**
