### PR TITLE
Feature/add azure adaptor

### PR DESCRIPTION
**Pull request by jarvisjohnson**
Adds an adaptor to upload to Azure using Azure's 'blobs' feature

### CODE REVIEW

**Comment by jarvisjohnson** [comment]
PR: https://github.com/kjvarga/sitemap_generator/pull/323

**Comment by jarvisjohnson** [comment]
Hey @kjvarga what do you think of this PR?  Let me know if you get a chance to look please.

**Comment by kjvarga** [comment]
@jarvisjohnson thanks for the PR!  It generally looks good to me.  I can take a closer look later, but could you please add some tests.

**Comment by jarvisjohnson** [comment]
Ok sounds good @kjvarga - I'll build some tests in shortly 👍

**Comment by kjvarga** [comment]
Closing due to inactivity.

**Pull request closed without merging**
