### PR TITLE
Allow Fog public option to be Configurable

### PR DESCRIPTION
**Pull request by mstruve**
Hi!

We are currently [using sitemap_generator](https://github.com/forem/forem/blob/master/config/sitemap.rb) in our Forem project. One issue we are having is that we cannot get it to work with IAM profiles because the Fog option `public` is set to true and we need it set to false. 

This PR allows the user to set the Fog `public` option however they see fit but will default to true if not present. 

Let me know what you think!

### CODE REVIEW

**Comment by FireFart** [comment]
@kjvarga any chance to get this merged? We are running into the same issue (https://github.com/kjvarga/sitemap_generator/issues/365)

**Comment by Lordnibbler** [comment]
@kjvarga apologies to ping, but 1.5 years is a long time to wait for a bug fix :( any way to get this merged?

**Comment by kjvarga** [comment]
Hi folks, sorry for the delay.  I'll be able to merge this soon as I'm putting together a new release :)

**Review by kjvarga — APPROVED** [review]

**Comment by kjvarga** [comment]
This is merged.  If you could please test it out and let me know if there are any problems.  I'll release it soon.

**Comment by kjvarga** [comment]
Released in 6.2.0

**Comment by codyrobbins** [comment]
I've created a pull request for a similar modification for `AwsSdkAdapter` at https://github.com/kjvarga/sitemap_generator/pull/394.

**Pull request merged**
