### PR TITLE
Fixes issue #396 from upstream repo

### PR DESCRIPTION
**Pull request by goandgit**
Just combined [tkhsh](https://github.com/tkhsh) commits for #396 / #397 and #399 into one for ease of merging. Tests are passing for me.

### CODE REVIEW

**Comment by kjvarga** [comment]
Sorry I’ve been busy but will address this this weekend

**Comment by goandgit** [comment]
It's ok. I'm going to rescind this PR as even though the tests pass it's still not working:
`Google::Apis::ClientError: invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access`


#<HTTP::Message:0x00007f63c48fc788 @http_header=#<HTTP::Message::Headers:0x00007f63c48fc760 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x5500 URI:https://storage.googleapis.com/storage/v1/b/dev-saverd-sitemap?>, @request_query=nil, @request_absolute_uri=nil, @status_code=200, @reason_phrase="OK", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["X-GUploader-UploadID", "ADPycdsmXXJdTF4vXqjgJ_cCynrdNQ2kHunP9xokk2fnv8nY6Aob3vB0RyRr2lvRPD9mX-23AOv_9MAwe5OUUVI8hNhxLQ"], ["ETag", "CAM="], ["Content-Type", "application/json; charset=UTF-8"], ["Date", "Thu, 14 Jul 2022 20:55:25 GMT"], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Cache-Control", "private, max-age=0, must-revalidate, no-transform"], ["Expires", "Thu, 14 Jul 2022 20:55:25 GMT"], ["Content-Length", "722"], ["Server", "UploadServer"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=storage.googleapis.com>, issuer=#<OpenSSL::X509::Name CN=GTS CA 1C3,O=Google Trust Services LLC,C=US>, serial=#<OpenSSL::BN:0x00007f63c4921358>, not_before=2022-06-27 08:27:50 UTC, not_after=2022-09-19 08:27:49 UTC>, @http_body=#<HTTP::Message::Body:0x00007f63c48fc5f8 @body="{\n  \"kind\": \"storage#bucket\",\n  \"selfLink\": \"https://www.googleapis.com/storage/v1/b/dev-saverd-sitemap\",\n  \"id\": \"dev-saverd-sitemap\",\n  \"name\": \"dev-saverd-sitemap\",\n  \"projectNumber\": \"361818651045\",\n  \"metageneration\": \"3\",\n  \"location\": \"US\",\n  \"storageClass\": \"STANDARD\",\n  \"etag\": \"CAM=\",\n  \"timeCreated\": \"2022-07-14T18:52:48.333Z\",\n  \"updated\": \"2022-07-14T20:49:50.647Z\",\n  \"iamConfiguration\": {\n    \"bucketPolicyOnly\": {\n      \"enabled\": true,\n      \"lockedTime\": \"2022-10-12T18:52:48.333Z\"\n    },\n    \"uniformBucketLevelAccess\": {\n      \"enabled\": true,\n      \"lockedTime\": \"2022-10-12T18:52:48.333Z\"\n    },\n    \"publicAccessPrevention\": \"inherited\"\n  },\n  \"locationType\": \"multi-region\",\n  \"rpo\": \"DEFAULT\"\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
Success - #<Google::Apis::StorageV1::Bucket:0x00007f63c4927910
 @etag="CAM=",
 @iam_configuration=
  #<Google::Apis::StorageV1::Bucket::IamConfiguration:0x00007f63c494f898
   @bucket_policy_only=
    #<Google::Apis::StorageV1::Bucket::IamConfiguration::BucketPolicyOnly:0x00007f63c489f538
     @enabled=true,
     @locked_time=Wed, 12 Oct 2022 18:52:48 +0000>,
   @public_access_prevention="inherited",
   @uniform_bucket_level_access=
    #<Google::Apis::StorageV1::Bucket::IamConfiguration::UniformBucketLevelAccess:0x00007f63c48ae998
     @enabled=true,
     @locked_time=Wed, 12 Oct 2022 18:52:48 +0000>>,
 @id="dev-sitemap",
 @kind="storage#bucket",
 @location="US",
 @location_type="multi-region",
 @metageneration=3,
 @name="dev-sitemap",
 @project_number=361818651045,
 @rpo="DEFAULT",
 @self_link="https://www.googleapis.com/storage/v1/b/dev-sitemap",
 @storage_class="STANDARD",
 @time_created=Thu, 14 Jul 2022 18:52:48 +0000,
 @updated=Thu, 14 Jul 2022 20:49:50 +0000>

Sending upload start command to https://storage.googleapis.com/upload/storage/v1/b/dev-sitemap/o?name=sitemap.xml.gz&predefinedAcl=publicRead
Upload status active
Sending upload command to https://storage.googleapis.com/upload/storage/v1/b/dev-sitemap/o?name=sitemap.xml.gz&predefinedAcl=publicRead&upload_id=ADPycdvSc8oHPWiTVGCOjDYT3gwDO6W-Ct1Gyuv5zzgzG_csaq7Z_38QGWbZEj4UVybo4XUwWwO9dAOZhCR2lfg3y-OvkQ&upload_protocol=resumable
Upload status final
Error - #<Google::Apis::ClientError: invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access status_code: 400 header: #<HTTP::Message::Headers:0x00007f63c48146e0 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x5528 URI:https://storage.googleapis.com/upload/storage/v1/b/dev-saverd-sitemap/o?name=sitemap.xml.gz&predefinedAcl=publicRead&upload_id=ADPycdvSc8oHPWiTVGCOjDYT3gwDO6W-Ct1Gyuv5zzgzG_csaq7Z_38QGWbZEj4UVybo4XUwWwO9dAOZhCR2lfg3y-OvkQ&upload_protocol=resumable>, @request_query=nil, @request_absolute_uri=nil, @status_code=400, @reason_phrase="Bad Request", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["X-GUploader-UploadID", "ADPycdvSc8oHPWiTVGCOjDYT3gwDO6W-Ct1Gyuv5zzgzG_csaq7Z_38QGWbZEj4UVybo4XUwWwO9dAOZhCR2lfg3y-OvkQ"], ["X-Goog-Upload-Status", "final"], ["Content-Type", "application/json; charset=UTF-8"], ["Date", "Thu, 14 Jul 2022 20:55:25 GMT"], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Cache-Control", "no-cache, no-store, max-age=0, must-revalidate"], ["Expires", "Mon, 01 Jan 1990 00:00:00 GMT"], ["Pragma", "no-cache"], ["Content-Length", "498"], ["Server", "UploadServer"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\""]], @dumped=false> body: "{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access\",\n    \"errors\": [\n      {\n        \"message\": \"Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access\",\n        \"domain\": \"global\",\n        \"reason\": \"invalid\"\n      }\n    ]\n  }\n}\n">

**Comment by goandgit** [comment]
I suspect incorrect permissions in Google Cloud Storage. I've gone back to S3 and everything is working but this till might be worth a merge. I see no reason why the changes wouldn't work. So I'll leave the PR open so you can close if you see fit. Sorry I couldn't be of more help.

**Comment by kjvarga** [comment]
Thanks.  I've incorporated the changes in https://github.com/kjvarga/sitemap_generator/pull/410.  

The error you got seems to be because you have bucket-level access configured, which means you can't specify ACL file-level access.  I'm not sure if that means that this won't work well for most people or not.  But since we're not changing the current bahaviour we can go ahead with this.  My guess is that you'll need to explicitly pass `acl: nil` if you have bucket-level access configured.  See https://cloud.google.com/storage/docs/uniform-bucket-level-access

**Pull request closed without merging**
