### PR TITLE
Enabled support for specifiying S3 Endpoints for S3 Compliant Providers

### PR DESCRIPTION
**Pull request by rjhancock**
Updated to allow for using S3-Compliant providers such as DigitalOcean Spaces.

Updated README to include minimal needed for S3.

### CODE REVIEW

**Comment by rjhancock** [comment]
Is there any way I can encourage this to be properly merged?

**Comment by kandayo** [comment]
Thank you.

**Comment by jmarbach** [comment]
@kjvarga Would you be able to review and merge this PR? It seems like adding this endpoint option will enable any S3-compatible API, such as DigitalOcean Spaces.

More support for this functionality:
https://stackoverflow.com/questions/61276322/cant-specify-digitalocean-endpoint-in-sitemap-generator-s3-aws-adaptor

**Comment by kjvarga** [comment]
Looks reasonable.  I'll try to get to it soon

**Comment by rjhancock** [comment]
Shall I update with fixes for the readme?

**Comment by kjvarga** [comment]
@rjhancock yes please

**Comment by rjhancock** [comment]
Pulled in all updates and fixed the README.

**Comment by rjhancock** [comment]
@kjvarga Just pinging to put back on the radar (if it wasn't already) as it looks like others are wanting this as well.

I know you're probably busy so whenever you got the time.

**Comment by kjvarga** [comment]
Released in v6.1.1

**Pull request merged**
