### PR TITLE
Upgrade to aws-sdk-s3 (v3) from aws-sdk (v2)

### PR DESCRIPTION
**Pull request by bitsapien**
This closes issue #289

### CODE REVIEW

**Comment by leikind** [comment]
There is really no point in loading all libraries for all AWS services while AWS SDK version 3 is modularized: https://github.com/kjvarga/sitemap_generator/pull/293

**Comment by bitsapien** [comment]
@kjvarga Will you please take a look at this and drop in your observations ?

**Comment by kjvarga** [comment]
@bitsapien funnily enough, requiring these external libraries in the adapter has caused the most code churn as these external dependencies evolve.  So I've decided to not handle the `require` myself.  Instead I'll raise an error if the classes that the adapter uses are not defined.  And leave it up to the user to require whatever libs they need.

That will put these issues to rest for good.  I've got things pretty close to release, at which time I'll put a comment in here and close this issue.

**Comment by leikind** [comment]
It's an option, provided it's described well in the docs.

**Comment by kjvarga** [comment]
I've release v6.0.0 of the gem.  In this version, the user must `require` whichever library they like, rather than leave that up to the SitemapGenerator gem to do.

See https://github.com/kjvarga/sitemap_generator#supported-adapters

**Pull request closed without merging**
