### PR TITLE
Use LoadError for unavailable adapters.

### PR DESCRIPTION
**Pull request by robotdana**
To allow sorbet to work and not crash during its requiring everything step,
raise LoadError rather than RuntimeError. sorbet expects to see
LoadError sometimes and will rescue LoadError but doesn't know what to
do with RuntimeError

I notice in #344 you mention that you don't believe it counts as a
LoadError because you're looking for the constant to already be defined
however i think the LoadError in this case is not being able to load
e.g. the sitemap_generator/adapters/s3_adapter.rb file itself, rather than
the LoadError being Aws::S3::Resource is undefined.

And for sheer practicality, if you change it to LoadError sorbet can
continue. but if you don't change it to LoadError in order to use sorbet
we either have to add the 5 gems unecessarily or stop using
sitemap_generator entirely

to replicate:

1. create a Gemfile in a new dir
```ruby
source 'https://rubygems.org'

gem 'sorbet'
gem 'sitemap_generator'
```
the directory can be otherwise entirely empty

2. `bundle install`
3. `bundle exec srb init`
4. say Y when asked

previously it would stop at a RuntimeError when requiring all the
autoloads and immediately raising because the gem being adapted isn't
there.
now LoadErrors are reported but sorbet can continue.

fixes: #345, fixes: #344, fixes: #339

### CODE REVIEW

**Comment by jrochkind** [comment]
(I'm just an observing fellow user, but LoadError seems reasonable to me, despite not being a sorbet user).

**Comment by dogweather** [comment]
My workaround for using with sorbet:

Gemfile:

```ruby
gem 'sitemap_generator', require: !!ENV['RAKE_ENVIRONMENT'] unless !!ENV['SRB_RBI_UPDATE']
```

Then I invoke Sorbet like this:

```bash
env SRB_RBI_UPDATE=1 bundle exec srb rbi update
```

**Comment by kjvarga** [comment]
@robotdana this sounds reasonable.  I used to raise a `LoadError` but that changed a while ago.  A few people use Sorbet and I haven't had a suggestion on how to be compatible until now, so thanks.  I've merged this to `master` via https://github.com/kjvarga/sitemap_generator/pull/387.   Can you confirm that Sorbet is okay with this now?  I'll release soon.

**Comment by robotdana** [comment]
looks good :)

**Comment by kjvarga** [comment]
Released in 6.2.0

**Pull request closed without merging**
